# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 20:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import about_me.importers.orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('primary_email', models.EmailField(max_length=100)),
                ('secondary_email', models.EmailField(blank=True, max_length=100)),
                ('primary_mobile', models.CharField(max_length=20, null=True)),
                ('secondary_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('unique_pin', models.CharField(default=about_me.importers.orders.models.pin, editable=False, max_length=6, unique=True)),
            ],
            options={
                'ordering': ['client'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.BooleanField(default=False)),
                ('driver', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Order No.')),
                ('due', models.DateTimeField(default=datetime.datetime(2017, 8, 24, 22, 11, 18, 756691))),
                ('status', models.CharField(blank=True, choices=[('', 'Packing'), ('0', 'Awaiting Delivery'), ('1', 'In Transit'), ('2', 'Delivered')], max_length=100)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('delivered_by', models.CharField(default='-', editable=False, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('', '- Select -'), ('(Bn)', 'Beans'), ('(Flt)', 'Filter'), ('(C)', 'Capsules'), ('(CM)', 'Coffee Machine'), ('(IC)', 'Instant Coffees'), ('(T)', 'Teas'), ('(IHB)', 'Instant Hot Beverages'), ('(S)', 'Smoothies'), ('(Con)', 'Consumables'), ('(C&L)', 'Take away cups and lids'), ('(CMC)', 'Coffee Machine Consumables')], max_length=100, verbose_name='Description')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('volume', models.CharField(max_length=100, verbose_name='Volume')),
                ('product_code', models.CharField(max_length=5, verbose_name='Code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ('description', 'name', 'volume', 'product_code'),
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('order_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Product')),
            ],
        ),
    ]
