# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 23:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170830_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 1, 41, 51, 404469)),
        ),
    ]
