# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 23:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20171021_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 1, 58, 52, 674049)),
        ),
    ]
