# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-08 00:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20171021_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 9, 2, 51, 56, 386233)),
        ),
    ]
