# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-09 00:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20180109_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 10, 2, 44, 59, 626372)),
        ),
    ]
