# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-13 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180110_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 14, 14, 5, 23, 780463)),
        ),
    ]
