# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-16 05:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180115_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 16, 23, 31, 47, 73459)),
        ),
    ]
