# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-10 05:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180117_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 23, 0, 4, 458175)),
        ),
    ]
