# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-04 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180309_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 5, 14, 52, 46, 349647)),
        ),
    ]
